addi        PASSED
add         PASSED
auipc       PASSED
BEQ         PASSED
JAL         PASSED
lui         PASSED
lw          PASSED
rebouclage  PASSED
sll         PASSED
slt         PASSED
sub         PASSED
sw          PASSED
