addi        PASSED
add         PASSED
andi        PASSED
and         PASSED
auipc       PASSED
BEQ         PASSED
bge         PASSED
bgeu        PASSED
blt         PASSED
bltu        PASSED
bne         PASSED
jalr        PASSED
JAL         PASSED
lb          PASSED
lbu         PASSED
lh          PASSED
lhu         PASSED
lui         PASSED
lw          PASSED
ori         PASSED
or          PASSED
rebouclage  PASSED
slli        PASSED
sll         PASSED
slti        PASSED
sltiu       PASSED
slt         PASSED
sltu        PASSED
srai        PASSED
sra         PASSED
srli        PASSED
srl         PASSED
sub         PASSED
sw          TIMEOUT
xori        PASSED
xor         PASSED
